model: vllm
model_args: "pretrained=moonshotai/Kimi-K2-Instruct,dtype=auto,load_format=safetensors,dtype=auto,gpu_memory_utilization=0.7,tensor_parallel_size=8,trust_remote_code=True"
batch_size: auto